[package]
name = "cardgame"
version = "0.1.0"
authors = ["Timothy <timothy.durbano@gmail.com>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
rand = "0.4.2"
log = "0.4.1"
l20n = "0.1.1"
bitflags = "1.0.1"